# Generated by Django 3.2.11 on 2023-03-24 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('cant_create_book', "Can't Create Book")]},
        ),
    ]
