# Generated by Django 3.2.11 on 2023-03-24 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
    ]
