# Generated by Django 3.2.11 on 2023-03-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about_me',
            field=models.TextField(default='', verbose_name='about me'),
        ),
    ]
